# This is a basic workflow to help you get started with Actions
#
#
#
# Test 0 - test yml


name: Mark0
env:
  APPLICATION_NAME       : "MyTest"
  DEPLOY_PACKAGE_NAME    : "Test_deploy_ver_${{ github.sha }}" #github.sha переменная
  
  

on:
  push:
    branches:
      - main 
      #Push in master branch
      
jobs:
  # This workflow contains a single job called "build"
  my_testing: 
    runs-on: ubuntu-latest
  
  #build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello_World
        run: echo "Hello World Testing job"
      
      - name: Execure few comands
        run: |
          echo "Hello 1"
          echo "Hello 2"
          echo "application name: ${{ env.APPLICATION_NAME }}"
      - name:  List current folder
        run: ls -la
        
  my_deploy: 
    runs-on: ubuntu-latest
    needs: my_testing #начнет стартовать только после выполнения 1 job "My testing"
    
    steps: 
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"
        
      - name: Deployment package name
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
